"""Initial schema creation

Revision ID: fd6475f7beae
Revises: 
Create Date: 2025-10-02 01:21:01.213419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd6475f7beae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    op.drop_table('transactions')
    op.drop_table('write_off_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('write_off_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('write_off_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='write_off_types_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('transactions',
    sa.Column('transaction_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('processing_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount_card_currency', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('commission', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('write_off_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('transactions_source_id_fkey')),
    sa.ForeignKeyConstraint(['write_off_type_id'], ['write_off_types.id'], name=op.f('transactions_write_off_type_id_fkey')),
    sa.PrimaryKeyConstraint('transaction_datetime', 'amount', 'source_id', 'write_off_type_id', name=op.f('transactions_pk'))
    )
    op.create_table('sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sources_pkey')),
    sa.UniqueConstraint('code', name=op.f('sources_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
